# Generated by Django 6.0.5 on 2026-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(blank=True, to='clients.client'),
        ),
    ]
