# Generated by Django 6.0.5 on 2026-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cell_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
    ]
