# Generated by Django 6.0.5 on 2026-06-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_approved_amount_event_client_event_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventguest',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='eventguest',
            name='to_invite',
        ),
    ]
