# Generated by Django 6.0.5 on 2026-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_budget_line_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('CONFERENCE', 'Conference'), ('MEETING', 'Meeting'), ('PARTY', 'Party'), ('FUNDRAISER', 'Fundraiser'), ('DONATION', 'Donation'), ('OTHER', 'Other')], default='', max_length=20),
        ),
    ]
