# Generated by Django 6.0.5 on 2026-06-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlineitem',
            name='category',
            field=models.CharField(choices=[('materials', 'Materials'), ('venue', 'Venue'), ('swag', 'Swag'), ('tickets', 'Tickets'), ('donations', 'Donations'), ('travel', 'Travel'), ('sponsorships', 'Sponsorships'), ('misc', 'Misc')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('CONFERENCE', 'Conference'), ('MEETING', 'Meeting'), ('PARTY', 'Party'), ('FUNDRAISER', 'Fundraiser'), ('DONATION', 'Donation'), ('AWARDS', 'Awards'), ('OTHER', 'Other')], default='', max_length=20),
        ),
    ]
