# Generated by Django 6.0.5 on 2026-06-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_end_date_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='added_on_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
