# Generated by Django 6.0.5 on 2026-06-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_calendar_event_id_eventguest_added_on_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlineitem',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='proposed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='proposed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
