# Generated by Django 6.0.5 on 2026-06-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_widen_decimal_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_edit_events', 'Can create and edit events, people, and companies')]},
        ),
    ]
