# Generated by Django 6.0.5 on 2026-06-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email_client_phone'),
        ('people', '0003_person_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
    ]
