# Generated by Django 6.0.5 on 2026-06-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_contact_person'),
        ('people', '0003_person_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for', to='people.person'),
        ),
    ]
