# Generated by Django 6.0.5 on 2026-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_contact_person_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='market_area',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
