# Generated by Django 6.0.5 on 2026-06-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('people', '0004_person_cell_phone_number_person_is_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
    ]
